"""Entity base classes.

Mirrors the Java modelet.entity package: an entity is a plain dataclass that
knows its table name, its key fields, and which transaction mode (INSERT /
UPDATE / DELETE) the next ``save()`` should perform.

Field-to-column mapping uses the dataclass field name by default. Two metadata
keys are recognized, named after their Jakarta Persistence counterparts:

- ``field(metadata={"column": "bookName"})`` maps a field to a differently
  named column (like ``@Column(name=...)``).
- ``field(metadata={"transient": True})`` excludes a field from generated SQL
  (like ``@Transient`` / Java Modelet's ``getExclusiveFields()``).
"""

from __future__ import annotations

import dataclasses
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any, ClassVar


class TxnMode(Enum):
    INSERT = "insert"
    UPDATE = "update"
    DELETE = "delete"
    SELECT = "select"


@dataclass
class Entity:
    """Base class for persistable entities.

    Modelet assumes each entity has an ``id`` field as primary key. By default
    the id is generated by the database and written back to the entity after a
    successful insert; set ``system_increment = True`` on the class if your
    application generates ids itself.

    A freshly constructed entity is in INSERT mode. After a successful insert,
    or when loaded from the database, it switches to UPDATE mode. Set
    ``txn_mode = TxnMode.DELETE`` before ``save()`` to delete it.
    """

    id: Any = None

    # -- class-level configuration (never persisted) --
    table_name: ClassVar[str | None] = None
    key_names: ClassVar[tuple[str, ...]] = ("id",)
    exclusive_fields: ClassVar[tuple[str, ...]] = ()
    system_increment: ClassVar[bool] = False
    allow_null_value: ClassVar[bool] = False

    def __post_init__(self):
        # deliberately not a dataclass field so it never leaks into SQL
        self.txn_mode = TxnMode.INSERT

    def get_table_name(self) -> str:
        if self.table_name:
            return self.table_name
        return type(self).__name__.lower()

    @property
    def is_new(self) -> bool:
        return self.id is None

    def before_save(self):
        """Called right before the entity is converted to a SQL statement."""

    def after_save(self):
        """Called right after the entity is written to the database."""


@dataclass
class AppEntity(Entity):
    """Entity with audit columns, filled in automatically on save when a login
    is present in ``modelet.context`` (mirrors Java's AppEntity)."""

    create_date: datetime | None = None
    creator: str | None = None
    modify_date: datetime | None = None
    modifier: str | None = None


def column_name(f: dataclasses.Field) -> str:
    return f.metadata.get("column", f.name)


def persistent_fields(entity: Entity) -> list[dataclasses.Field]:
    """Fields that participate in generated SQL, honoring ``transient``
    metadata and the class-level ``exclusive_fields`` list."""
    fields = []
    for f in dataclasses.fields(entity):
        if f.metadata.get("transient"):
            continue
        if f.name in type(entity).exclusive_fields:
            continue
        fields.append(f)
    return fields
